// Code generated by protoc-gen-go. DO NOT EDIT.
// source: error.proto

package runm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FaultCode int32

const (
	// Some HTTP-like codes
	FaultCode_NOT_FOUND FaultCode = 0
	FaultCode_DUPLICATE FaultCode = 1
	FaultCode_BAD_INPUT FaultCode = 2
	FaultCode_NO_AUTH   FaultCode = 3
	FaultCode_FORBIDDEN FaultCode = 4
	FaultCode_TIMEOUT   FaultCode = 5
	// More domain-specific errors
	FaultCode_GENERATION_CONFLICT FaultCode = 100
	FaultCode_UNKNOWN             FaultCode = 9999
)

var FaultCode_name = map[int32]string{
	0:    "NOT_FOUND",
	1:    "DUPLICATE",
	2:    "BAD_INPUT",
	3:    "NO_AUTH",
	4:    "FORBIDDEN",
	5:    "TIMEOUT",
	100:  "GENERATION_CONFLICT",
	9999: "UNKNOWN",
}
var FaultCode_value = map[string]int32{
	"NOT_FOUND":           0,
	"DUPLICATE":           1,
	"BAD_INPUT":           2,
	"NO_AUTH":             3,
	"FORBIDDEN":           4,
	"TIMEOUT":             5,
	"GENERATION_CONFLICT": 100,
	"UNKNOWN":             9999,
}

func (x FaultCode) String() string {
	return proto.EnumName(FaultCode_name, int32(x))
}
func (FaultCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_error_7e63cfd7c81cd3ca, []int{0}
}

// Information about individual errors that may have occurred
type Error struct {
	FaultCode            FaultCode `protobuf:"varint,1,opt,name=fault_code,json=faultCode,enum=runm.FaultCode" json:"fault_code,omitempty"`
	ErrorText            string    `protobuf:"bytes,2,opt,name=error_text,json=errorText" json:"error_text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_error_7e63cfd7c81cd3ca, []int{0}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetFaultCode() FaultCode {
	if m != nil {
		return m.FaultCode
	}
	return FaultCode_NOT_FOUND
}

func (m *Error) GetErrorText() string {
	if m != nil {
		return m.ErrorText
	}
	return ""
}

func init() {
	proto.RegisterType((*Error)(nil), "runm.Error")
	proto.RegisterEnum("runm.FaultCode", FaultCode_name, FaultCode_value)
}

func init() { proto.RegisterFile("error.proto", fileDescriptor_error_7e63cfd7c81cd3ca) }

var fileDescriptor_error_7e63cfd7c81cd3ca = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0xc6, 0x4d, 0x6d, 0x2d, 0x99, 0xfa, 0x27, 0xc4, 0x83, 0xbd, 0x08, 0xc5, 0x53, 0xf1, 0xb0,
	0x07, 0x7d, 0x82, 0xed, 0x26, 0xab, 0xc1, 0x3a, 0x29, 0xcb, 0x44, 0x8f, 0x41, 0xdd, 0xf4, 0xa4,
	0x46, 0x42, 0x0a, 0x7d, 0x04, 0x6f, 0xbe, 0xb2, 0x64, 0x41, 0x6f, 0xf3, 0xfd, 0x7e, 0x33, 0x03,
	0x1f, 0xcc, 0x42, 0x4a, 0x31, 0x55, 0x5f, 0x29, 0xe6, 0x28, 0xc7, 0x69, 0xf7, 0xf9, 0x71, 0xf5,
	0x04, 0x13, 0x5d, 0xa0, 0xac, 0x00, 0xb6, 0x2f, 0xbb, 0xf7, 0xec, 0xdf, 0x62, 0x1f, 0xe6, 0x6c,
	0xc1, 0x96, 0xa7, 0x37, 0x67, 0x55, 0xd9, 0xa9, 0xda, 0xc2, 0x9b, 0xd8, 0x87, 0x8e, 0x6f, 0xff,
	0x46, 0x79, 0x09, 0x30, 0x7c, 0xf3, 0x39, 0xec, 0xf3, 0x7c, 0xb4, 0x60, 0x4b, 0xde, 0xf1, 0x81,
	0x50, 0xd8, 0xe7, 0xeb, 0x6f, 0x06, 0xfc, 0xff, 0x4e, 0x9e, 0x00, 0x47, 0x4b, 0xbe, 0xb5, 0x0e,
	0x95, 0x38, 0x28, 0x51, 0xb9, 0xcd, 0xda, 0x34, 0x35, 0x69, 0xc1, 0x4a, 0x5c, 0xd5, 0xca, 0x1b,
	0xdc, 0x38, 0x12, 0x23, 0x39, 0x83, 0x29, 0x5a, 0x5f, 0x3b, 0xba, 0x17, 0x87, 0xc5, 0xb5, 0xb6,
	0x5b, 0x19, 0xa5, 0x34, 0x8a, 0x71, 0x71, 0x64, 0x1e, 0xb5, 0x75, 0x24, 0x26, 0xf2, 0x02, 0xce,
	0xef, 0x34, 0xea, 0xae, 0x26, 0x63, 0xd1, 0x37, 0x16, 0xdb, 0xb5, 0x69, 0x48, 0xf4, 0xf2, 0x18,
	0xa6, 0x0e, 0x1f, 0xd0, 0x3e, 0xa3, 0xf8, 0xc1, 0xd7, 0xa3, 0xa1, 0xef, 0xed, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xfa, 0x7f, 0xc4, 0xdd, 0xfe, 0x00, 0x00, 0x00,
}
