// Code generated by protoc-gen-go. DO NOT EDIT.
// source: permission.proto

package runm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Types of permissions for actions that may be taken with runm
type Permission int32

const (
	Permission_SUPER          Permission = 0
	Permission_READ_ANY       Permission = 1
	Permission_READ_PROJECT   Permission = 2
	Permission_READ_USER      Permission = 3
	Permission_CREATE_ANY     Permission = 1001
	Permission_CREATE_PROJECT Permission = 1002
	Permission_CREATE_USER    Permission = 1003
	Permission_MODIFY_ANY     Permission = 2001
	Permission_MODIFY_PROJECT Permission = 2002
	Permission_MODIFY_USER    Permission = 2003
	Permission_DELETE_ANY     Permission = 3001
	Permission_DELETE_PROJECT Permission = 3002
	Permission_DELETE_USER    Permission = 3003
	Permission_END_PERMS      Permission = 999999
)

var Permission_name = map[int32]string{
	0:      "SUPER",
	1:      "READ_ANY",
	2:      "READ_PROJECT",
	3:      "READ_USER",
	1001:   "CREATE_ANY",
	1002:   "CREATE_PROJECT",
	1003:   "CREATE_USER",
	2001:   "MODIFY_ANY",
	2002:   "MODIFY_PROJECT",
	2003:   "MODIFY_USER",
	3001:   "DELETE_ANY",
	3002:   "DELETE_PROJECT",
	3003:   "DELETE_USER",
	999999: "END_PERMS",
}
var Permission_value = map[string]int32{
	"SUPER":          0,
	"READ_ANY":       1,
	"READ_PROJECT":   2,
	"READ_USER":      3,
	"CREATE_ANY":     1001,
	"CREATE_PROJECT": 1002,
	"CREATE_USER":    1003,
	"MODIFY_ANY":     2001,
	"MODIFY_PROJECT": 2002,
	"MODIFY_USER":    2003,
	"DELETE_ANY":     3001,
	"DELETE_PROJECT": 3002,
	"DELETE_USER":    3003,
	"END_PERMS":      999999,
}

func (x Permission) String() string {
	return proto.EnumName(Permission_name, int32(x))
}
func (Permission) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_permission_dbaaa40f74e4cf4d, []int{0}
}

// Note: this wrapper message is needed because protobuf doesn't support
// map<string, repeated Permission>...
type PermissionSet struct {
	Permissions          []Permission `protobuf:"varint,1,rep,packed,name=permissions,enum=runm.Permission" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PermissionSet) Reset()         { *m = PermissionSet{} }
func (m *PermissionSet) String() string { return proto.CompactTextString(m) }
func (*PermissionSet) ProtoMessage()    {}
func (*PermissionSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_permission_dbaaa40f74e4cf4d, []int{0}
}
func (m *PermissionSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionSet.Unmarshal(m, b)
}
func (m *PermissionSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionSet.Marshal(b, m, deterministic)
}
func (dst *PermissionSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionSet.Merge(dst, src)
}
func (m *PermissionSet) XXX_Size() int {
	return xxx_messageInfo_PermissionSet.Size(m)
}
func (m *PermissionSet) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionSet.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionSet proto.InternalMessageInfo

func (m *PermissionSet) GetPermissions() []Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func init() {
	proto.RegisterType((*PermissionSet)(nil), "runm.PermissionSet")
	proto.RegisterEnum("runm.Permission", Permission_name, Permission_value)
}

func init() { proto.RegisterFile("permission.proto", fileDescriptor_permission_dbaaa40f74e4cf4d) }

var fileDescriptor_permission_dbaaa40f74e4cf4d = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x48, 0x2d, 0xca,
	0xcd, 0x2c, 0x2e, 0xce, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x29, 0x2a,
	0xcd, 0xcb, 0x55, 0x72, 0xe6, 0xe2, 0x0d, 0x80, 0xcb, 0x04, 0xa7, 0x96, 0x08, 0x19, 0x71, 0x71,
	0x23, 0x94, 0x16, 0x4b, 0x30, 0x2a, 0x30, 0x6b, 0xf0, 0x19, 0x09, 0xe8, 0x81, 0x14, 0xeb, 0x21,
	0x54, 0x06, 0x21, 0x2b, 0xd2, 0xfa, 0xcf, 0xc8, 0xc5, 0x85, 0x90, 0x13, 0xe2, 0xe4, 0x62, 0x0d,
	0x0e, 0x0d, 0x70, 0x0d, 0x12, 0x60, 0x10, 0xe2, 0xe1, 0xe2, 0x08, 0x72, 0x75, 0x74, 0x89, 0x77,
	0xf4, 0x8b, 0x14, 0x60, 0x14, 0x12, 0xe0, 0xe2, 0x01, 0xf3, 0x02, 0x82, 0xfc, 0xbd, 0x5c, 0x9d,
	0x43, 0x04, 0x98, 0x84, 0x78, 0xb9, 0x38, 0xc1, 0x22, 0xa1, 0xc1, 0xae, 0x41, 0x02, 0xcc, 0x42,
	0xfc, 0x5c, 0x5c, 0xce, 0x41, 0xae, 0x8e, 0x21, 0xae, 0x60, 0x0d, 0x2f, 0xd9, 0x85, 0x84, 0xb9,
	0xf8, 0xa0, 0x02, 0x30, 0x3d, 0xaf, 0xd8, 0x85, 0x04, 0xb8, 0xb8, 0xa1, 0x82, 0x60, 0x6d, 0xaf,
	0xd9, 0x41, 0xfa, 0x7c, 0xfd, 0x5d, 0x3c, 0xdd, 0x22, 0xc1, 0xfa, 0x2e, 0xf2, 0x83, 0xf4, 0x41,
	0x05, 0x60, 0xfa, 0x2e, 0xf1, 0x83, 0xf4, 0x41, 0x05, 0xc1, 0xfa, 0x2e, 0xf3, 0x83, 0xf4, 0xb9,
	0xb8, 0xfa, 0xb8, 0x42, 0xed, 0xdb, 0x29, 0x0e, 0xd2, 0x07, 0x15, 0x80, 0xe9, 0xdb, 0x25, 0x0e,
	0xd2, 0x07, 0x15, 0x04, 0xeb, 0xdb, 0x2d, 0x2e, 0xc4, 0xcf, 0xc5, 0xe9, 0xea, 0xe7, 0x12, 0x1f,
	0xe0, 0x1a, 0xe4, 0x1b, 0x2c, 0xb0, 0xbf, 0xc5, 0x36, 0x89, 0x0d, 0x1c, 0xa6, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x2e, 0xcc, 0xc2, 0xc3, 0x67, 0x01, 0x00, 0x00,
}
