// Code generated by protoc-gen-go. DO NOT EDIT.
// source: search.proto

package runm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SortDirection int32

const (
	SortDirection_ASC  SortDirection = 0
	SortDirection_DESC SortDirection = 1
)

var SortDirection_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}
var SortDirection_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x SortDirection) String() string {
	return proto.EnumName(SortDirection_name, int32(x))
}
func (SortDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_search_6e09b0261f2e31e5, []int{0}
}

type SortField struct {
	Field                string        `protobuf:"bytes,1,opt,name=field" json:"field,omitempty"`
	Direction            SortDirection `protobuf:"varint,2,opt,name=direction,enum=runm.SortDirection" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SortField) Reset()         { *m = SortField{} }
func (m *SortField) String() string { return proto.CompactTextString(m) }
func (*SortField) ProtoMessage()    {}
func (*SortField) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_6e09b0261f2e31e5, []int{0}
}
func (m *SortField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SortField.Unmarshal(m, b)
}
func (m *SortField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SortField.Marshal(b, m, deterministic)
}
func (dst *SortField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SortField.Merge(dst, src)
}
func (m *SortField) XXX_Size() int {
	return xxx_messageInfo_SortField.Size(m)
}
func (m *SortField) XXX_DiscardUnknown() {
	xxx_messageInfo_SortField.DiscardUnknown(m)
}

var xxx_messageInfo_SortField proto.InternalMessageInfo

func (m *SortField) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *SortField) GetDirection() SortDirection {
	if m != nil {
		return m.Direction
	}
	return SortDirection_ASC
}

// Options for sorting and pagination of list queries
type SearchOptions struct {
	Limit                uint32       `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Marker               string       `protobuf:"bytes,2,opt,name=marker" json:"marker,omitempty"`
	SortFields           []*SortField `protobuf:"bytes,3,rep,name=sort_fields,json=sortFields" json:"sort_fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SearchOptions) Reset()         { *m = SearchOptions{} }
func (m *SearchOptions) String() string { return proto.CompactTextString(m) }
func (*SearchOptions) ProtoMessage()    {}
func (*SearchOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_6e09b0261f2e31e5, []int{1}
}
func (m *SearchOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchOptions.Unmarshal(m, b)
}
func (m *SearchOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchOptions.Marshal(b, m, deterministic)
}
func (dst *SearchOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchOptions.Merge(dst, src)
}
func (m *SearchOptions) XXX_Size() int {
	return xxx_messageInfo_SearchOptions.Size(m)
}
func (m *SearchOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchOptions.DiscardUnknown(m)
}

var xxx_messageInfo_SearchOptions proto.InternalMessageInfo

func (m *SearchOptions) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchOptions) GetMarker() string {
	if m != nil {
		return m.Marker
	}
	return ""
}

func (m *SearchOptions) GetSortFields() []*SortField {
	if m != nil {
		return m.SortFields
	}
	return nil
}

func init() {
	proto.RegisterType((*SortField)(nil), "runm.SortField")
	proto.RegisterType((*SearchOptions)(nil), "runm.SearchOptions")
	proto.RegisterEnum("runm.SortDirection", SortDirection_name, SortDirection_value)
}

func init() { proto.RegisterFile("search.proto", fileDescriptor_search_6e09b0261f2e31e5) }

var fileDescriptor_search_6e09b0261f2e31e5 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xcd, 0x4e, 0x84, 0x30,
	0x14, 0x85, 0xad, 0x20, 0xda, 0x8b, 0x28, 0xa9, 0xc6, 0xb0, 0x24, 0xac, 0x88, 0x0b, 0xa2, 0xf8,
	0x04, 0x06, 0x74, 0x6b, 0xd2, 0xba, 0x37, 0x08, 0x35, 0x36, 0x02, 0x25, 0xb7, 0xf5, 0xfd, 0x27,
	0x2d, 0x43, 0xc8, 0xec, 0xce, 0x97, 0xf6, 0xfc, 0x5c, 0xb8, 0x36, 0xb2, 0xc3, 0xfe, 0xb7, 0x5a,
	0x50, 0x5b, 0xcd, 0x42, 0xfc, 0x9f, 0xa7, 0xe2, 0x13, 0xa8, 0xd0, 0x68, 0xdf, 0x95, 0x1c, 0x07,
	0x76, 0x0f, 0x17, 0x3f, 0x4e, 0x64, 0x24, 0x27, 0x25, 0xe5, 0x2b, 0xb0, 0x67, 0xa0, 0x83, 0x42,
	0xd9, 0x5b, 0xa5, 0xe7, 0xec, 0x3c, 0x27, 0xe5, 0x4d, 0x7d, 0x57, 0x39, 0x73, 0xe5, 0x9c, 0xed,
	0xf6, 0xc4, 0xf7, 0x5f, 0x85, 0x86, 0x44, 0xf8, 0xae, 0x8f, 0xc5, 0xb1, 0x71, 0xc9, 0xa3, 0x9a,
	0x94, 0xf5, 0xc9, 0x09, 0x5f, 0x81, 0x3d, 0x40, 0x34, 0x75, 0xf8, 0x27, 0xd1, 0xc7, 0x52, 0x7e,
	0x24, 0xf6, 0x04, 0xb1, 0xd1, 0x68, 0xbf, 0x7c, 0xbf, 0xc9, 0x82, 0x3c, 0x28, 0xe3, 0xfa, 0x76,
	0xef, 0xf4, 0x6b, 0x39, 0x98, 0x4d, 0x9a, 0xc7, 0x02, 0x92, 0x93, 0x31, 0xec, 0x12, 0x82, 0x57,
	0xd1, 0xa4, 0x67, 0xec, 0x0a, 0xc2, 0xf6, 0x4d, 0x34, 0x29, 0xf9, 0x8e, 0xfc, 0xdd, 0x2f, 0x87,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xd1, 0x40, 0x1d, 0x07, 0x01, 0x00, 0x00,
}
