// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package runm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PayloadFormat int32

const (
	PayloadFormat_YAML        PayloadFormat = 0
	PayloadFormat_PROTOBUFFER PayloadFormat = 1
)

var PayloadFormat_name = map[int32]string{
	0: "YAML",
	1: "PROTOBUFFER",
}
var PayloadFormat_value = map[string]int32{
	"YAML":        0,
	"PROTOBUFFER": 1,
}

func (x PayloadFormat) String() string {
	return proto.EnumName(PayloadFormat_name, int32(x))
}
func (PayloadFormat) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_service_6147864b9035fd4a, []int{0}
}

type BootstrapRequest struct {
	// The value of the one-time bootstrap token. This must match exactly the
	// value of the `--bootstrap-token` used when starting the metadata service
	// and this is destroyed at the successful execution of a bootstrap
	// operation.
	BootstrapToken string `protobuf:"bytes,1,opt,name=bootstrap_token,json=bootstrapToken" json:"bootstrap_token,omitempty"`
	// A human-readable name for the partition you want to ensure exists
	PartitionName string `protobuf:"bytes,2,opt,name=partition_name,json=partitionName" json:"partition_name,omitempty"`
	// Useful if you want to pre-determine partition UUIDs or during testing
	PartitionUuid        *StringValue `protobuf:"bytes,3,opt,name=partition_uuid,json=partitionUuid" json:"partition_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BootstrapRequest) Reset()         { *m = BootstrapRequest{} }
func (m *BootstrapRequest) String() string { return proto.CompactTextString(m) }
func (*BootstrapRequest) ProtoMessage()    {}
func (*BootstrapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6147864b9035fd4a, []int{0}
}
func (m *BootstrapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BootstrapRequest.Unmarshal(m, b)
}
func (m *BootstrapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BootstrapRequest.Marshal(b, m, deterministic)
}
func (dst *BootstrapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BootstrapRequest.Merge(dst, src)
}
func (m *BootstrapRequest) XXX_Size() int {
	return xxx_messageInfo_BootstrapRequest.Size(m)
}
func (m *BootstrapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BootstrapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BootstrapRequest proto.InternalMessageInfo

func (m *BootstrapRequest) GetBootstrapToken() string {
	if m != nil {
		return m.BootstrapToken
	}
	return ""
}

func (m *BootstrapRequest) GetPartitionName() string {
	if m != nil {
		return m.PartitionName
	}
	return ""
}

func (m *BootstrapRequest) GetPartitionUuid() *StringValue {
	if m != nil {
		return m.PartitionUuid
	}
	return nil
}

type BootstrapResponse struct {
	// The partition that was created as part of the bootstrap process
	Partition            *Partition `protobuf:"bytes,1,opt,name=partition" json:"partition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BootstrapResponse) Reset()         { *m = BootstrapResponse{} }
func (m *BootstrapResponse) String() string { return proto.CompactTextString(m) }
func (*BootstrapResponse) ProtoMessage()    {}
func (*BootstrapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6147864b9035fd4a, []int{1}
}
func (m *BootstrapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BootstrapResponse.Unmarshal(m, b)
}
func (m *BootstrapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BootstrapResponse.Marshal(b, m, deterministic)
}
func (dst *BootstrapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BootstrapResponse.Merge(dst, src)
}
func (m *BootstrapResponse) XXX_Size() int {
	return xxx_messageInfo_BootstrapResponse.Size(m)
}
func (m *BootstrapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BootstrapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BootstrapResponse proto.InternalMessageInfo

func (m *BootstrapResponse) GetPartition() *Partition {
	if m != nil {
		return m.Partition
	}
	return nil
}

type PartitionGetRequest struct {
	Session              *Session         `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Filter               *PartitionFilter `protobuf:"bytes,2,opt,name=filter" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PartitionGetRequest) Reset()         { *m = PartitionGetRequest{} }
func (m *PartitionGetRequest) String() string { return proto.CompactTextString(m) }
func (*PartitionGetRequest) ProtoMessage()    {}
func (*PartitionGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6147864b9035fd4a, []int{2}
}
func (m *PartitionGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionGetRequest.Unmarshal(m, b)
}
func (m *PartitionGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionGetRequest.Marshal(b, m, deterministic)
}
func (dst *PartitionGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionGetRequest.Merge(dst, src)
}
func (m *PartitionGetRequest) XXX_Size() int {
	return xxx_messageInfo_PartitionGetRequest.Size(m)
}
func (m *PartitionGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionGetRequest proto.InternalMessageInfo

func (m *PartitionGetRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *PartitionGetRequest) GetFilter() *PartitionFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type PartitionListRequest struct {
	Session              *Session           `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Options              *SearchOptions     `protobuf:"bytes,2,opt,name=options" json:"options,omitempty"`
	Any                  []*PartitionFilter `protobuf:"bytes,3,rep,name=any" json:"any,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PartitionListRequest) Reset()         { *m = PartitionListRequest{} }
func (m *PartitionListRequest) String() string { return proto.CompactTextString(m) }
func (*PartitionListRequest) ProtoMessage()    {}
func (*PartitionListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6147864b9035fd4a, []int{3}
}
func (m *PartitionListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionListRequest.Unmarshal(m, b)
}
func (m *PartitionListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionListRequest.Marshal(b, m, deterministic)
}
func (dst *PartitionListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionListRequest.Merge(dst, src)
}
func (m *PartitionListRequest) XXX_Size() int {
	return xxx_messageInfo_PartitionListRequest.Size(m)
}
func (m *PartitionListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionListRequest proto.InternalMessageInfo

func (m *PartitionListRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *PartitionListRequest) GetOptions() *SearchOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *PartitionListRequest) GetAny() []*PartitionFilter {
	if m != nil {
		return m.Any
	}
	return nil
}

type ObjectTypeGetRequest struct {
	Session              *Session          `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Filter               *ObjectTypeFilter `protobuf:"bytes,2,opt,name=filter" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ObjectTypeGetRequest) Reset()         { *m = ObjectTypeGetRequest{} }
func (m *ObjectTypeGetRequest) String() string { return proto.CompactTextString(m) }
func (*ObjectTypeGetRequest) ProtoMessage()    {}
func (*ObjectTypeGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6147864b9035fd4a, []int{4}
}
func (m *ObjectTypeGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectTypeGetRequest.Unmarshal(m, b)
}
func (m *ObjectTypeGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectTypeGetRequest.Marshal(b, m, deterministic)
}
func (dst *ObjectTypeGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectTypeGetRequest.Merge(dst, src)
}
func (m *ObjectTypeGetRequest) XXX_Size() int {
	return xxx_messageInfo_ObjectTypeGetRequest.Size(m)
}
func (m *ObjectTypeGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectTypeGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectTypeGetRequest proto.InternalMessageInfo

func (m *ObjectTypeGetRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *ObjectTypeGetRequest) GetFilter() *ObjectTypeFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type ObjectTypeListRequest struct {
	Session *Session       `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Options *SearchOptions `protobuf:"bytes,2,opt,name=options" json:"options,omitempty"`
	// A set of filter expressions that are OR'd together when determining
	// matches
	Any                  []*ObjectTypeFilter `protobuf:"bytes,3,rep,name=any" json:"any,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ObjectTypeListRequest) Reset()         { *m = ObjectTypeListRequest{} }
func (m *ObjectTypeListRequest) String() string { return proto.CompactTextString(m) }
func (*ObjectTypeListRequest) ProtoMessage()    {}
func (*ObjectTypeListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6147864b9035fd4a, []int{5}
}
func (m *ObjectTypeListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectTypeListRequest.Unmarshal(m, b)
}
func (m *ObjectTypeListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectTypeListRequest.Marshal(b, m, deterministic)
}
func (dst *ObjectTypeListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectTypeListRequest.Merge(dst, src)
}
func (m *ObjectTypeListRequest) XXX_Size() int {
	return xxx_messageInfo_ObjectTypeListRequest.Size(m)
}
func (m *ObjectTypeListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectTypeListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectTypeListRequest proto.InternalMessageInfo

func (m *ObjectTypeListRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *ObjectTypeListRequest) GetOptions() *SearchOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *ObjectTypeListRequest) GetAny() []*ObjectTypeFilter {
	if m != nil {
		return m.Any
	}
	return nil
}

type ObjectGetRequest struct {
	Session              *Session      `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Filter               *ObjectFilter `protobuf:"bytes,2,opt,name=filter" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ObjectGetRequest) Reset()         { *m = ObjectGetRequest{} }
func (m *ObjectGetRequest) String() string { return proto.CompactTextString(m) }
func (*ObjectGetRequest) ProtoMessage()    {}
func (*ObjectGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6147864b9035fd4a, []int{6}
}
func (m *ObjectGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectGetRequest.Unmarshal(m, b)
}
func (m *ObjectGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectGetRequest.Marshal(b, m, deterministic)
}
func (dst *ObjectGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectGetRequest.Merge(dst, src)
}
func (m *ObjectGetRequest) XXX_Size() int {
	return xxx_messageInfo_ObjectGetRequest.Size(m)
}
func (m *ObjectGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectGetRequest proto.InternalMessageInfo

func (m *ObjectGetRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *ObjectGetRequest) GetFilter() *ObjectFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type ObjectSetRequest struct {
	Session *Session      `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Format  PayloadFormat `protobuf:"varint,2,opt,name=format,enum=runm.PayloadFormat" json:"format,omitempty"`
	// Raw bytes representing the new representation of the object. The server
	// is responsible for unmarshaling this raw payload.
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectSetRequest) Reset()         { *m = ObjectSetRequest{} }
func (m *ObjectSetRequest) String() string { return proto.CompactTextString(m) }
func (*ObjectSetRequest) ProtoMessage()    {}
func (*ObjectSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6147864b9035fd4a, []int{7}
}
func (m *ObjectSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectSetRequest.Unmarshal(m, b)
}
func (m *ObjectSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectSetRequest.Marshal(b, m, deterministic)
}
func (dst *ObjectSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectSetRequest.Merge(dst, src)
}
func (m *ObjectSetRequest) XXX_Size() int {
	return xxx_messageInfo_ObjectSetRequest.Size(m)
}
func (m *ObjectSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectSetRequest proto.InternalMessageInfo

func (m *ObjectSetRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *ObjectSetRequest) GetFormat() PayloadFormat {
	if m != nil {
		return m.Format
	}
	return PayloadFormat_YAML
}

func (m *ObjectSetRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ObjectSetResponse struct {
	// The changed/created object
	Object               *Object  `protobuf:"bytes,1,opt,name=object" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectSetResponse) Reset()         { *m = ObjectSetResponse{} }
func (m *ObjectSetResponse) String() string { return proto.CompactTextString(m) }
func (*ObjectSetResponse) ProtoMessage()    {}
func (*ObjectSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6147864b9035fd4a, []int{8}
}
func (m *ObjectSetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectSetResponse.Unmarshal(m, b)
}
func (m *ObjectSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectSetResponse.Marshal(b, m, deterministic)
}
func (dst *ObjectSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectSetResponse.Merge(dst, src)
}
func (m *ObjectSetResponse) XXX_Size() int {
	return xxx_messageInfo_ObjectSetResponse.Size(m)
}
func (m *ObjectSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectSetResponse proto.InternalMessageInfo

func (m *ObjectSetResponse) GetObject() *Object {
	if m != nil {
		return m.Object
	}
	return nil
}

type ObjectListRequest struct {
	Session *Session       `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Options *SearchOptions `protobuf:"bytes,2,opt,name=options" json:"options,omitempty"`
	// A set of filter expressions that are OR'd together when determining
	// matches
	Any                  []*ObjectFilter `protobuf:"bytes,3,rep,name=any" json:"any,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ObjectListRequest) Reset()         { *m = ObjectListRequest{} }
func (m *ObjectListRequest) String() string { return proto.CompactTextString(m) }
func (*ObjectListRequest) ProtoMessage()    {}
func (*ObjectListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6147864b9035fd4a, []int{9}
}
func (m *ObjectListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectListRequest.Unmarshal(m, b)
}
func (m *ObjectListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectListRequest.Marshal(b, m, deterministic)
}
func (dst *ObjectListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectListRequest.Merge(dst, src)
}
func (m *ObjectListRequest) XXX_Size() int {
	return xxx_messageInfo_ObjectListRequest.Size(m)
}
func (m *ObjectListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectListRequest proto.InternalMessageInfo

func (m *ObjectListRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *ObjectListRequest) GetOptions() *SearchOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *ObjectListRequest) GetAny() []*ObjectFilter {
	if m != nil {
		return m.Any
	}
	return nil
}

type ObjectDeleteRequest struct {
	Session *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	// A set of filter expressions that are OR'd together when determining
	// matches for deletion
	Any                  []*ObjectFilter `protobuf:"bytes,2,rep,name=any" json:"any,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ObjectDeleteRequest) Reset()         { *m = ObjectDeleteRequest{} }
func (m *ObjectDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*ObjectDeleteRequest) ProtoMessage()    {}
func (*ObjectDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6147864b9035fd4a, []int{10}
}
func (m *ObjectDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectDeleteRequest.Unmarshal(m, b)
}
func (m *ObjectDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectDeleteRequest.Marshal(b, m, deterministic)
}
func (dst *ObjectDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectDeleteRequest.Merge(dst, src)
}
func (m *ObjectDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_ObjectDeleteRequest.Size(m)
}
func (m *ObjectDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectDeleteRequest proto.InternalMessageInfo

func (m *ObjectDeleteRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *ObjectDeleteRequest) GetAny() []*ObjectFilter {
	if m != nil {
		return m.Any
	}
	return nil
}

type ObjectDeleteResponse struct {
	Errors               []string `protobuf:"bytes,1,rep,name=errors" json:"errors,omitempty"`
	NumDeleted           uint64   `protobuf:"varint,2,opt,name=num_deleted,json=numDeleted" json:"num_deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectDeleteResponse) Reset()         { *m = ObjectDeleteResponse{} }
func (m *ObjectDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*ObjectDeleteResponse) ProtoMessage()    {}
func (*ObjectDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6147864b9035fd4a, []int{11}
}
func (m *ObjectDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectDeleteResponse.Unmarshal(m, b)
}
func (m *ObjectDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectDeleteResponse.Marshal(b, m, deterministic)
}
func (dst *ObjectDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectDeleteResponse.Merge(dst, src)
}
func (m *ObjectDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_ObjectDeleteResponse.Size(m)
}
func (m *ObjectDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectDeleteResponse proto.InternalMessageInfo

func (m *ObjectDeleteResponse) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *ObjectDeleteResponse) GetNumDeleted() uint64 {
	if m != nil {
		return m.NumDeleted
	}
	return 0
}

type PropertyDefinitionGetRequest struct {
	Session              *Session                  `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Filter               *PropertyDefinitionFilter `protobuf:"bytes,2,opt,name=filter" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *PropertyDefinitionGetRequest) Reset()         { *m = PropertyDefinitionGetRequest{} }
func (m *PropertyDefinitionGetRequest) String() string { return proto.CompactTextString(m) }
func (*PropertyDefinitionGetRequest) ProtoMessage()    {}
func (*PropertyDefinitionGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6147864b9035fd4a, []int{12}
}
func (m *PropertyDefinitionGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropertyDefinitionGetRequest.Unmarshal(m, b)
}
func (m *PropertyDefinitionGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropertyDefinitionGetRequest.Marshal(b, m, deterministic)
}
func (dst *PropertyDefinitionGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropertyDefinitionGetRequest.Merge(dst, src)
}
func (m *PropertyDefinitionGetRequest) XXX_Size() int {
	return xxx_messageInfo_PropertyDefinitionGetRequest.Size(m)
}
func (m *PropertyDefinitionGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PropertyDefinitionGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PropertyDefinitionGetRequest proto.InternalMessageInfo

func (m *PropertyDefinitionGetRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *PropertyDefinitionGetRequest) GetFilter() *PropertyDefinitionFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type PropertyDefinitionSetRequest struct {
	Session *Session      `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Format  PayloadFormat `protobuf:"varint,2,opt,name=format,enum=runm.PayloadFormat" json:"format,omitempty"`
	// Raw bytes representing the new representation of the property definition.
	// The server is responsible for unmarshaling this raw payload.
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PropertyDefinitionSetRequest) Reset()         { *m = PropertyDefinitionSetRequest{} }
func (m *PropertyDefinitionSetRequest) String() string { return proto.CompactTextString(m) }
func (*PropertyDefinitionSetRequest) ProtoMessage()    {}
func (*PropertyDefinitionSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6147864b9035fd4a, []int{13}
}
func (m *PropertyDefinitionSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropertyDefinitionSetRequest.Unmarshal(m, b)
}
func (m *PropertyDefinitionSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropertyDefinitionSetRequest.Marshal(b, m, deterministic)
}
func (dst *PropertyDefinitionSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropertyDefinitionSetRequest.Merge(dst, src)
}
func (m *PropertyDefinitionSetRequest) XXX_Size() int {
	return xxx_messageInfo_PropertyDefinitionSetRequest.Size(m)
}
func (m *PropertyDefinitionSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PropertyDefinitionSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PropertyDefinitionSetRequest proto.InternalMessageInfo

func (m *PropertyDefinitionSetRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *PropertyDefinitionSetRequest) GetFormat() PayloadFormat {
	if m != nil {
		return m.Format
	}
	return PayloadFormat_YAML
}

func (m *PropertyDefinitionSetRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type PropertyDefinitionSetResponse struct {
	PropertyDefinition   *PropertyDefinition `protobuf:"bytes,2,opt,name=property_definition,json=propertyDefinition" json:"property_definition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PropertyDefinitionSetResponse) Reset()         { *m = PropertyDefinitionSetResponse{} }
func (m *PropertyDefinitionSetResponse) String() string { return proto.CompactTextString(m) }
func (*PropertyDefinitionSetResponse) ProtoMessage()    {}
func (*PropertyDefinitionSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6147864b9035fd4a, []int{14}
}
func (m *PropertyDefinitionSetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropertyDefinitionSetResponse.Unmarshal(m, b)
}
func (m *PropertyDefinitionSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropertyDefinitionSetResponse.Marshal(b, m, deterministic)
}
func (dst *PropertyDefinitionSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropertyDefinitionSetResponse.Merge(dst, src)
}
func (m *PropertyDefinitionSetResponse) XXX_Size() int {
	return xxx_messageInfo_PropertyDefinitionSetResponse.Size(m)
}
func (m *PropertyDefinitionSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PropertyDefinitionSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PropertyDefinitionSetResponse proto.InternalMessageInfo

func (m *PropertyDefinitionSetResponse) GetPropertyDefinition() *PropertyDefinition {
	if m != nil {
		return m.PropertyDefinition
	}
	return nil
}

type PropertyDefinitionListRequest struct {
	Session *Session       `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Options *SearchOptions `protobuf:"bytes,2,opt,name=options" json:"options,omitempty"`
	// A set of filter expressions that are OR'd together when determining
	// matches
	Any                  []*PropertyDefinitionFilter `protobuf:"bytes,3,rep,name=any" json:"any,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *PropertyDefinitionListRequest) Reset()         { *m = PropertyDefinitionListRequest{} }
func (m *PropertyDefinitionListRequest) String() string { return proto.CompactTextString(m) }
func (*PropertyDefinitionListRequest) ProtoMessage()    {}
func (*PropertyDefinitionListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6147864b9035fd4a, []int{15}
}
func (m *PropertyDefinitionListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropertyDefinitionListRequest.Unmarshal(m, b)
}
func (m *PropertyDefinitionListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropertyDefinitionListRequest.Marshal(b, m, deterministic)
}
func (dst *PropertyDefinitionListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropertyDefinitionListRequest.Merge(dst, src)
}
func (m *PropertyDefinitionListRequest) XXX_Size() int {
	return xxx_messageInfo_PropertyDefinitionListRequest.Size(m)
}
func (m *PropertyDefinitionListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PropertyDefinitionListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PropertyDefinitionListRequest proto.InternalMessageInfo

func (m *PropertyDefinitionListRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *PropertyDefinitionListRequest) GetOptions() *SearchOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *PropertyDefinitionListRequest) GetAny() []*PropertyDefinitionFilter {
	if m != nil {
		return m.Any
	}
	return nil
}

type PropertyDefinitionDeleteRequest struct {
	Session *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	// A set of filter expressions that are OR'd together when determining
	// matches
	Any                  []*PropertyDefinitionFilter `protobuf:"bytes,2,rep,name=any" json:"any,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *PropertyDefinitionDeleteRequest) Reset()         { *m = PropertyDefinitionDeleteRequest{} }
func (m *PropertyDefinitionDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*PropertyDefinitionDeleteRequest) ProtoMessage()    {}
func (*PropertyDefinitionDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6147864b9035fd4a, []int{16}
}
func (m *PropertyDefinitionDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropertyDefinitionDeleteRequest.Unmarshal(m, b)
}
func (m *PropertyDefinitionDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropertyDefinitionDeleteRequest.Marshal(b, m, deterministic)
}
func (dst *PropertyDefinitionDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropertyDefinitionDeleteRequest.Merge(dst, src)
}
func (m *PropertyDefinitionDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_PropertyDefinitionDeleteRequest.Size(m)
}
func (m *PropertyDefinitionDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PropertyDefinitionDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PropertyDefinitionDeleteRequest proto.InternalMessageInfo

func (m *PropertyDefinitionDeleteRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *PropertyDefinitionDeleteRequest) GetAny() []*PropertyDefinitionFilter {
	if m != nil {
		return m.Any
	}
	return nil
}

type PropertyDefinitionDeleteResponse struct {
	Errors               []string `protobuf:"bytes,1,rep,name=errors" json:"errors,omitempty"`
	NumDeleted           uint64   `protobuf:"varint,2,opt,name=num_deleted,json=numDeleted" json:"num_deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PropertyDefinitionDeleteResponse) Reset()         { *m = PropertyDefinitionDeleteResponse{} }
func (m *PropertyDefinitionDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*PropertyDefinitionDeleteResponse) ProtoMessage()    {}
func (*PropertyDefinitionDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6147864b9035fd4a, []int{17}
}
func (m *PropertyDefinitionDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropertyDefinitionDeleteResponse.Unmarshal(m, b)
}
func (m *PropertyDefinitionDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropertyDefinitionDeleteResponse.Marshal(b, m, deterministic)
}
func (dst *PropertyDefinitionDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropertyDefinitionDeleteResponse.Merge(dst, src)
}
func (m *PropertyDefinitionDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_PropertyDefinitionDeleteResponse.Size(m)
}
func (m *PropertyDefinitionDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PropertyDefinitionDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PropertyDefinitionDeleteResponse proto.InternalMessageInfo

func (m *PropertyDefinitionDeleteResponse) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *PropertyDefinitionDeleteResponse) GetNumDeleted() uint64 {
	if m != nil {
		return m.NumDeleted
	}
	return 0
}

type ObjectPropertiesSetRequest struct {
	Session              *Session    `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Object               *Object     `protobuf:"bytes,2,opt,name=object" json:"object,omitempty"`
	Add                  []*Property `protobuf:"bytes,3,rep,name=add" json:"add,omitempty"`
	Remove               []*Property `protobuf:"bytes,4,rep,name=remove" json:"remove,omitempty"`
	Modify               []*Property `protobuf:"bytes,5,rep,name=modify" json:"modify,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ObjectPropertiesSetRequest) Reset()         { *m = ObjectPropertiesSetRequest{} }
func (m *ObjectPropertiesSetRequest) String() string { return proto.CompactTextString(m) }
func (*ObjectPropertiesSetRequest) ProtoMessage()    {}
func (*ObjectPropertiesSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6147864b9035fd4a, []int{18}
}
func (m *ObjectPropertiesSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectPropertiesSetRequest.Unmarshal(m, b)
}
func (m *ObjectPropertiesSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectPropertiesSetRequest.Marshal(b, m, deterministic)
}
func (dst *ObjectPropertiesSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectPropertiesSetRequest.Merge(dst, src)
}
func (m *ObjectPropertiesSetRequest) XXX_Size() int {
	return xxx_messageInfo_ObjectPropertiesSetRequest.Size(m)
}
func (m *ObjectPropertiesSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectPropertiesSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectPropertiesSetRequest proto.InternalMessageInfo

func (m *ObjectPropertiesSetRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *ObjectPropertiesSetRequest) GetObject() *Object {
	if m != nil {
		return m.Object
	}
	return nil
}

func (m *ObjectPropertiesSetRequest) GetAdd() []*Property {
	if m != nil {
		return m.Add
	}
	return nil
}

func (m *ObjectPropertiesSetRequest) GetRemove() []*Property {
	if m != nil {
		return m.Remove
	}
	return nil
}

func (m *ObjectPropertiesSetRequest) GetModify() []*Property {
	if m != nil {
		return m.Modify
	}
	return nil
}

type ObjectPropertiesSetResponse struct {
	Errors               []*Error `protobuf:"bytes,1,rep,name=errors" json:"errors,omitempty"`
	Object               *Object  `protobuf:"bytes,2,opt,name=object" json:"object,omitempty"`
	NumAdded             uint64   `protobuf:"varint,3,opt,name=num_added,json=numAdded" json:"num_added,omitempty"`
	NumRemoved           uint64   `protobuf:"varint,4,opt,name=num_removed,json=numRemoved" json:"num_removed,omitempty"`
	NumModified          uint64   `protobuf:"varint,5,opt,name=num_modified,json=numModified" json:"num_modified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectPropertiesSetResponse) Reset()         { *m = ObjectPropertiesSetResponse{} }
func (m *ObjectPropertiesSetResponse) String() string { return proto.CompactTextString(m) }
func (*ObjectPropertiesSetResponse) ProtoMessage()    {}
func (*ObjectPropertiesSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6147864b9035fd4a, []int{19}
}
func (m *ObjectPropertiesSetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectPropertiesSetResponse.Unmarshal(m, b)
}
func (m *ObjectPropertiesSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectPropertiesSetResponse.Marshal(b, m, deterministic)
}
func (dst *ObjectPropertiesSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectPropertiesSetResponse.Merge(dst, src)
}
func (m *ObjectPropertiesSetResponse) XXX_Size() int {
	return xxx_messageInfo_ObjectPropertiesSetResponse.Size(m)
}
func (m *ObjectPropertiesSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectPropertiesSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectPropertiesSetResponse proto.InternalMessageInfo

func (m *ObjectPropertiesSetResponse) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *ObjectPropertiesSetResponse) GetObject() *Object {
	if m != nil {
		return m.Object
	}
	return nil
}

func (m *ObjectPropertiesSetResponse) GetNumAdded() uint64 {
	if m != nil {
		return m.NumAdded
	}
	return 0
}

func (m *ObjectPropertiesSetResponse) GetNumRemoved() uint64 {
	if m != nil {
		return m.NumRemoved
	}
	return 0
}

func (m *ObjectPropertiesSetResponse) GetNumModified() uint64 {
	if m != nil {
		return m.NumModified
	}
	return 0
}

type ObjectPropertiesListFilters struct {
	// Used when searching for items with one or more keys, regardless of value
	Keys []string `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
	// Used when searching for items with one or more values, regardless of key
	Values []string `protobuf:"bytes,2,rep,name=values" json:"values,omitempty"`
	// Used when searching for specific key/value pairs
	Properties           []*Property `protobuf:"bytes,3,rep,name=properties" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ObjectPropertiesListFilters) Reset()         { *m = ObjectPropertiesListFilters{} }
func (m *ObjectPropertiesListFilters) String() string { return proto.CompactTextString(m) }
func (*ObjectPropertiesListFilters) ProtoMessage()    {}
func (*ObjectPropertiesListFilters) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6147864b9035fd4a, []int{20}
}
func (m *ObjectPropertiesListFilters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectPropertiesListFilters.Unmarshal(m, b)
}
func (m *ObjectPropertiesListFilters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectPropertiesListFilters.Marshal(b, m, deterministic)
}
func (dst *ObjectPropertiesListFilters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectPropertiesListFilters.Merge(dst, src)
}
func (m *ObjectPropertiesListFilters) XXX_Size() int {
	return xxx_messageInfo_ObjectPropertiesListFilters.Size(m)
}
func (m *ObjectPropertiesListFilters) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectPropertiesListFilters.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectPropertiesListFilters proto.InternalMessageInfo

func (m *ObjectPropertiesListFilters) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *ObjectPropertiesListFilters) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *ObjectPropertiesListFilters) GetProperties() []*Property {
	if m != nil {
		return m.Properties
	}
	return nil
}

type ObjectPropertiesListRequest struct {
	Session              *Session                     `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Object               *Object                      `protobuf:"bytes,2,opt,name=object" json:"object,omitempty"`
	Filters              *ObjectPropertiesListFilters `protobuf:"bytes,3,opt,name=filters" json:"filters,omitempty"`
	Options              *SearchOptions               `protobuf:"bytes,4,opt,name=options" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ObjectPropertiesListRequest) Reset()         { *m = ObjectPropertiesListRequest{} }
func (m *ObjectPropertiesListRequest) String() string { return proto.CompactTextString(m) }
func (*ObjectPropertiesListRequest) ProtoMessage()    {}
func (*ObjectPropertiesListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_6147864b9035fd4a, []int{21}
}
func (m *ObjectPropertiesListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectPropertiesListRequest.Unmarshal(m, b)
}
func (m *ObjectPropertiesListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectPropertiesListRequest.Marshal(b, m, deterministic)
}
func (dst *ObjectPropertiesListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectPropertiesListRequest.Merge(dst, src)
}
func (m *ObjectPropertiesListRequest) XXX_Size() int {
	return xxx_messageInfo_ObjectPropertiesListRequest.Size(m)
}
func (m *ObjectPropertiesListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectPropertiesListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectPropertiesListRequest proto.InternalMessageInfo

func (m *ObjectPropertiesListRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *ObjectPropertiesListRequest) GetObject() *Object {
	if m != nil {
		return m.Object
	}
	return nil
}

func (m *ObjectPropertiesListRequest) GetFilters() *ObjectPropertiesListFilters {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *ObjectPropertiesListRequest) GetOptions() *SearchOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func init() {
	proto.RegisterType((*BootstrapRequest)(nil), "runm.BootstrapRequest")
	proto.RegisterType((*BootstrapResponse)(nil), "runm.BootstrapResponse")
	proto.RegisterType((*PartitionGetRequest)(nil), "runm.PartitionGetRequest")
	proto.RegisterType((*PartitionListRequest)(nil), "runm.PartitionListRequest")
	proto.RegisterType((*ObjectTypeGetRequest)(nil), "runm.ObjectTypeGetRequest")
	proto.RegisterType((*ObjectTypeListRequest)(nil), "runm.ObjectTypeListRequest")
	proto.RegisterType((*ObjectGetRequest)(nil), "runm.ObjectGetRequest")
	proto.RegisterType((*ObjectSetRequest)(nil), "runm.ObjectSetRequest")
	proto.RegisterType((*ObjectSetResponse)(nil), "runm.ObjectSetResponse")
	proto.RegisterType((*ObjectListRequest)(nil), "runm.ObjectListRequest")
	proto.RegisterType((*ObjectDeleteRequest)(nil), "runm.ObjectDeleteRequest")
	proto.RegisterType((*ObjectDeleteResponse)(nil), "runm.ObjectDeleteResponse")
	proto.RegisterType((*PropertyDefinitionGetRequest)(nil), "runm.PropertyDefinitionGetRequest")
	proto.RegisterType((*PropertyDefinitionSetRequest)(nil), "runm.PropertyDefinitionSetRequest")
	proto.RegisterType((*PropertyDefinitionSetResponse)(nil), "runm.PropertyDefinitionSetResponse")
	proto.RegisterType((*PropertyDefinitionListRequest)(nil), "runm.PropertyDefinitionListRequest")
	proto.RegisterType((*PropertyDefinitionDeleteRequest)(nil), "runm.PropertyDefinitionDeleteRequest")
	proto.RegisterType((*PropertyDefinitionDeleteResponse)(nil), "runm.PropertyDefinitionDeleteResponse")
	proto.RegisterType((*ObjectPropertiesSetRequest)(nil), "runm.ObjectPropertiesSetRequest")
	proto.RegisterType((*ObjectPropertiesSetResponse)(nil), "runm.ObjectPropertiesSetResponse")
	proto.RegisterType((*ObjectPropertiesListFilters)(nil), "runm.ObjectPropertiesListFilters")
	proto.RegisterType((*ObjectPropertiesListRequest)(nil), "runm.ObjectPropertiesListRequest")
	proto.RegisterEnum("runm.PayloadFormat", PayloadFormat_name, PayloadFormat_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RunmMetadataClient is the client API for RunmMetadata service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RunmMetadataClient interface {
	// Creates minimal information for service to run, including a name for a
	// partition.
	Bootstrap(ctx context.Context, in *BootstrapRequest, opts ...grpc.CallOption) (*BootstrapResponse, error)
	// Returns information about a specific partition
	PartitionGet(ctx context.Context, in *PartitionGetRequest, opts ...grpc.CallOption) (*Partition, error)
	// Returns information about multiple partitions
	PartitionList(ctx context.Context, in *PartitionListRequest, opts ...grpc.CallOption) (RunmMetadata_PartitionListClient, error)
	// Returns information about a specific object type
	ObjectTypeGet(ctx context.Context, in *ObjectTypeGetRequest, opts ...grpc.CallOption) (*ObjectType, error)
	// Returns information about multiple object types
	ObjectTypeList(ctx context.Context, in *ObjectTypeListRequest, opts ...grpc.CallOption) (RunmMetadata_ObjectTypeListClient, error)
	// Returns information about a specific property definition
	PropertyDefinitionGet(ctx context.Context, in *PropertyDefinitionGetRequest, opts ...grpc.CallOption) (*PropertyDefinition, error)
	// Deletes one or more property definitions
	PropertyDefinitionDelete(ctx context.Context, in *PropertyDefinitionDeleteRequest, opts ...grpc.CallOption) (*PropertyDefinitionDeleteResponse, error)
	// Set information about a specific property definition
	PropertyDefinitionSet(ctx context.Context, in *PropertyDefinitionSetRequest, opts ...grpc.CallOption) (*PropertyDefinitionSetResponse, error)
	// Returns information about multiple property definitions
	PropertyDefinitionList(ctx context.Context, in *PropertyDefinitionListRequest, opts ...grpc.CallOption) (RunmMetadata_PropertyDefinitionListClient, error)
	// Returns information about a specific object
	ObjectGet(ctx context.Context, in *ObjectGetRequest, opts ...grpc.CallOption) (*Object, error)
	// Deletes one or more objectes
	ObjectDelete(ctx context.Context, in *ObjectDeleteRequest, opts ...grpc.CallOption) (*ObjectDeleteResponse, error)
	// Set information about a specific object
	ObjectSet(ctx context.Context, in *ObjectSetRequest, opts ...grpc.CallOption) (*ObjectSetResponse, error)
	// Returns information about multiple objects
	ObjectList(ctx context.Context, in *ObjectListRequest, opts ...grpc.CallOption) (RunmMetadata_ObjectListClient, error)
	// Add, remove or modify properties from an object
	ObjectPropertiesSet(ctx context.Context, in *ObjectPropertiesSetRequest, opts ...grpc.CallOption) (*ObjectPropertiesSetResponse, error)
	// Returns property items for an object
	ObjectPropertiesList(ctx context.Context, in *ObjectPropertiesListRequest, opts ...grpc.CallOption) (RunmMetadata_ObjectPropertiesListClient, error)
}

type runmMetadataClient struct {
	cc *grpc.ClientConn
}

func NewRunmMetadataClient(cc *grpc.ClientConn) RunmMetadataClient {
	return &runmMetadataClient{cc}
}

func (c *runmMetadataClient) Bootstrap(ctx context.Context, in *BootstrapRequest, opts ...grpc.CallOption) (*BootstrapResponse, error) {
	out := new(BootstrapResponse)
	err := c.cc.Invoke(ctx, "/runm.RunmMetadata/bootstrap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runmMetadataClient) PartitionGet(ctx context.Context, in *PartitionGetRequest, opts ...grpc.CallOption) (*Partition, error) {
	out := new(Partition)
	err := c.cc.Invoke(ctx, "/runm.RunmMetadata/partition_get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runmMetadataClient) PartitionList(ctx context.Context, in *PartitionListRequest, opts ...grpc.CallOption) (RunmMetadata_PartitionListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RunmMetadata_serviceDesc.Streams[0], "/runm.RunmMetadata/partition_list", opts...)
	if err != nil {
		return nil, err
	}
	x := &runmMetadataPartitionListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RunmMetadata_PartitionListClient interface {
	Recv() (*Partition, error)
	grpc.ClientStream
}

type runmMetadataPartitionListClient struct {
	grpc.ClientStream
}

func (x *runmMetadataPartitionListClient) Recv() (*Partition, error) {
	m := new(Partition)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *runmMetadataClient) ObjectTypeGet(ctx context.Context, in *ObjectTypeGetRequest, opts ...grpc.CallOption) (*ObjectType, error) {
	out := new(ObjectType)
	err := c.cc.Invoke(ctx, "/runm.RunmMetadata/object_type_get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runmMetadataClient) ObjectTypeList(ctx context.Context, in *ObjectTypeListRequest, opts ...grpc.CallOption) (RunmMetadata_ObjectTypeListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RunmMetadata_serviceDesc.Streams[1], "/runm.RunmMetadata/object_type_list", opts...)
	if err != nil {
		return nil, err
	}
	x := &runmMetadataObjectTypeListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RunmMetadata_ObjectTypeListClient interface {
	Recv() (*ObjectType, error)
	grpc.ClientStream
}

type runmMetadataObjectTypeListClient struct {
	grpc.ClientStream
}

func (x *runmMetadataObjectTypeListClient) Recv() (*ObjectType, error) {
	m := new(ObjectType)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *runmMetadataClient) PropertyDefinitionGet(ctx context.Context, in *PropertyDefinitionGetRequest, opts ...grpc.CallOption) (*PropertyDefinition, error) {
	out := new(PropertyDefinition)
	err := c.cc.Invoke(ctx, "/runm.RunmMetadata/property_definition_get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runmMetadataClient) PropertyDefinitionDelete(ctx context.Context, in *PropertyDefinitionDeleteRequest, opts ...grpc.CallOption) (*PropertyDefinitionDeleteResponse, error) {
	out := new(PropertyDefinitionDeleteResponse)
	err := c.cc.Invoke(ctx, "/runm.RunmMetadata/property_definition_delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runmMetadataClient) PropertyDefinitionSet(ctx context.Context, in *PropertyDefinitionSetRequest, opts ...grpc.CallOption) (*PropertyDefinitionSetResponse, error) {
	out := new(PropertyDefinitionSetResponse)
	err := c.cc.Invoke(ctx, "/runm.RunmMetadata/property_definition_set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runmMetadataClient) PropertyDefinitionList(ctx context.Context, in *PropertyDefinitionListRequest, opts ...grpc.CallOption) (RunmMetadata_PropertyDefinitionListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RunmMetadata_serviceDesc.Streams[2], "/runm.RunmMetadata/property_definition_list", opts...)
	if err != nil {
		return nil, err
	}
	x := &runmMetadataPropertyDefinitionListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RunmMetadata_PropertyDefinitionListClient interface {
	Recv() (*PropertyDefinition, error)
	grpc.ClientStream
}

type runmMetadataPropertyDefinitionListClient struct {
	grpc.ClientStream
}

func (x *runmMetadataPropertyDefinitionListClient) Recv() (*PropertyDefinition, error) {
	m := new(PropertyDefinition)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *runmMetadataClient) ObjectGet(ctx context.Context, in *ObjectGetRequest, opts ...grpc.CallOption) (*Object, error) {
	out := new(Object)
	err := c.cc.Invoke(ctx, "/runm.RunmMetadata/object_get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runmMetadataClient) ObjectDelete(ctx context.Context, in *ObjectDeleteRequest, opts ...grpc.CallOption) (*ObjectDeleteResponse, error) {
	out := new(ObjectDeleteResponse)
	err := c.cc.Invoke(ctx, "/runm.RunmMetadata/object_delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runmMetadataClient) ObjectSet(ctx context.Context, in *ObjectSetRequest, opts ...grpc.CallOption) (*ObjectSetResponse, error) {
	out := new(ObjectSetResponse)
	err := c.cc.Invoke(ctx, "/runm.RunmMetadata/object_set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runmMetadataClient) ObjectList(ctx context.Context, in *ObjectListRequest, opts ...grpc.CallOption) (RunmMetadata_ObjectListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RunmMetadata_serviceDesc.Streams[3], "/runm.RunmMetadata/object_list", opts...)
	if err != nil {
		return nil, err
	}
	x := &runmMetadataObjectListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RunmMetadata_ObjectListClient interface {
	Recv() (*Object, error)
	grpc.ClientStream
}

type runmMetadataObjectListClient struct {
	grpc.ClientStream
}

func (x *runmMetadataObjectListClient) Recv() (*Object, error) {
	m := new(Object)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *runmMetadataClient) ObjectPropertiesSet(ctx context.Context, in *ObjectPropertiesSetRequest, opts ...grpc.CallOption) (*ObjectPropertiesSetResponse, error) {
	out := new(ObjectPropertiesSetResponse)
	err := c.cc.Invoke(ctx, "/runm.RunmMetadata/object_properties_set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runmMetadataClient) ObjectPropertiesList(ctx context.Context, in *ObjectPropertiesListRequest, opts ...grpc.CallOption) (RunmMetadata_ObjectPropertiesListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RunmMetadata_serviceDesc.Streams[4], "/runm.RunmMetadata/object_properties_list", opts...)
	if err != nil {
		return nil, err
	}
	x := &runmMetadataObjectPropertiesListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RunmMetadata_ObjectPropertiesListClient interface {
	Recv() (*Property, error)
	grpc.ClientStream
}

type runmMetadataObjectPropertiesListClient struct {
	grpc.ClientStream
}

func (x *runmMetadataObjectPropertiesListClient) Recv() (*Property, error) {
	m := new(Property)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RunmMetadataServer is the server API for RunmMetadata service.
type RunmMetadataServer interface {
	// Creates minimal information for service to run, including a name for a
	// partition.
	Bootstrap(context.Context, *BootstrapRequest) (*BootstrapResponse, error)
	// Returns information about a specific partition
	PartitionGet(context.Context, *PartitionGetRequest) (*Partition, error)
	// Returns information about multiple partitions
	PartitionList(*PartitionListRequest, RunmMetadata_PartitionListServer) error
	// Returns information about a specific object type
	ObjectTypeGet(context.Context, *ObjectTypeGetRequest) (*ObjectType, error)
	// Returns information about multiple object types
	ObjectTypeList(*ObjectTypeListRequest, RunmMetadata_ObjectTypeListServer) error
	// Returns information about a specific property definition
	PropertyDefinitionGet(context.Context, *PropertyDefinitionGetRequest) (*PropertyDefinition, error)
	// Deletes one or more property definitions
	PropertyDefinitionDelete(context.Context, *PropertyDefinitionDeleteRequest) (*PropertyDefinitionDeleteResponse, error)
	// Set information about a specific property definition
	PropertyDefinitionSet(context.Context, *PropertyDefinitionSetRequest) (*PropertyDefinitionSetResponse, error)
	// Returns information about multiple property definitions
	PropertyDefinitionList(*PropertyDefinitionListRequest, RunmMetadata_PropertyDefinitionListServer) error
	// Returns information about a specific object
	ObjectGet(context.Context, *ObjectGetRequest) (*Object, error)
	// Deletes one or more objectes
	ObjectDelete(context.Context, *ObjectDeleteRequest) (*ObjectDeleteResponse, error)
	// Set information about a specific object
	ObjectSet(context.Context, *ObjectSetRequest) (*ObjectSetResponse, error)
	// Returns information about multiple objects
	ObjectList(*ObjectListRequest, RunmMetadata_ObjectListServer) error
	// Add, remove or modify properties from an object
	ObjectPropertiesSet(context.Context, *ObjectPropertiesSetRequest) (*ObjectPropertiesSetResponse, error)
	// Returns property items for an object
	ObjectPropertiesList(*ObjectPropertiesListRequest, RunmMetadata_ObjectPropertiesListServer) error
}

func RegisterRunmMetadataServer(s *grpc.Server, srv RunmMetadataServer) {
	s.RegisterService(&_RunmMetadata_serviceDesc, srv)
}

func _RunmMetadata_Bootstrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootstrapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunmMetadataServer).Bootstrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runm.RunmMetadata/Bootstrap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunmMetadataServer).Bootstrap(ctx, req.(*BootstrapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunmMetadata_PartitionGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartitionGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunmMetadataServer).PartitionGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runm.RunmMetadata/PartitionGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunmMetadataServer).PartitionGet(ctx, req.(*PartitionGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunmMetadata_PartitionList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PartitionListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunmMetadataServer).PartitionList(m, &runmMetadataPartitionListServer{stream})
}

type RunmMetadata_PartitionListServer interface {
	Send(*Partition) error
	grpc.ServerStream
}

type runmMetadataPartitionListServer struct {
	grpc.ServerStream
}

func (x *runmMetadataPartitionListServer) Send(m *Partition) error {
	return x.ServerStream.SendMsg(m)
}

func _RunmMetadata_ObjectTypeGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectTypeGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunmMetadataServer).ObjectTypeGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runm.RunmMetadata/ObjectTypeGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunmMetadataServer).ObjectTypeGet(ctx, req.(*ObjectTypeGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunmMetadata_ObjectTypeList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ObjectTypeListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunmMetadataServer).ObjectTypeList(m, &runmMetadataObjectTypeListServer{stream})
}

type RunmMetadata_ObjectTypeListServer interface {
	Send(*ObjectType) error
	grpc.ServerStream
}

type runmMetadataObjectTypeListServer struct {
	grpc.ServerStream
}

func (x *runmMetadataObjectTypeListServer) Send(m *ObjectType) error {
	return x.ServerStream.SendMsg(m)
}

func _RunmMetadata_PropertyDefinitionGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PropertyDefinitionGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunmMetadataServer).PropertyDefinitionGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runm.RunmMetadata/PropertyDefinitionGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunmMetadataServer).PropertyDefinitionGet(ctx, req.(*PropertyDefinitionGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunmMetadata_PropertyDefinitionDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PropertyDefinitionDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunmMetadataServer).PropertyDefinitionDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runm.RunmMetadata/PropertyDefinitionDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunmMetadataServer).PropertyDefinitionDelete(ctx, req.(*PropertyDefinitionDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunmMetadata_PropertyDefinitionSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PropertyDefinitionSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunmMetadataServer).PropertyDefinitionSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runm.RunmMetadata/PropertyDefinitionSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunmMetadataServer).PropertyDefinitionSet(ctx, req.(*PropertyDefinitionSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunmMetadata_PropertyDefinitionList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PropertyDefinitionListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunmMetadataServer).PropertyDefinitionList(m, &runmMetadataPropertyDefinitionListServer{stream})
}

type RunmMetadata_PropertyDefinitionListServer interface {
	Send(*PropertyDefinition) error
	grpc.ServerStream
}

type runmMetadataPropertyDefinitionListServer struct {
	grpc.ServerStream
}

func (x *runmMetadataPropertyDefinitionListServer) Send(m *PropertyDefinition) error {
	return x.ServerStream.SendMsg(m)
}

func _RunmMetadata_ObjectGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunmMetadataServer).ObjectGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runm.RunmMetadata/ObjectGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunmMetadataServer).ObjectGet(ctx, req.(*ObjectGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunmMetadata_ObjectDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunmMetadataServer).ObjectDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runm.RunmMetadata/ObjectDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunmMetadataServer).ObjectDelete(ctx, req.(*ObjectDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunmMetadata_ObjectSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunmMetadataServer).ObjectSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runm.RunmMetadata/ObjectSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunmMetadataServer).ObjectSet(ctx, req.(*ObjectSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunmMetadata_ObjectList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ObjectListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunmMetadataServer).ObjectList(m, &runmMetadataObjectListServer{stream})
}

type RunmMetadata_ObjectListServer interface {
	Send(*Object) error
	grpc.ServerStream
}

type runmMetadataObjectListServer struct {
	grpc.ServerStream
}

func (x *runmMetadataObjectListServer) Send(m *Object) error {
	return x.ServerStream.SendMsg(m)
}

func _RunmMetadata_ObjectPropertiesSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectPropertiesSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunmMetadataServer).ObjectPropertiesSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runm.RunmMetadata/ObjectPropertiesSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunmMetadataServer).ObjectPropertiesSet(ctx, req.(*ObjectPropertiesSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunmMetadata_ObjectPropertiesList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ObjectPropertiesListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunmMetadataServer).ObjectPropertiesList(m, &runmMetadataObjectPropertiesListServer{stream})
}

type RunmMetadata_ObjectPropertiesListServer interface {
	Send(*Property) error
	grpc.ServerStream
}

type runmMetadataObjectPropertiesListServer struct {
	grpc.ServerStream
}

func (x *runmMetadataObjectPropertiesListServer) Send(m *Property) error {
	return x.ServerStream.SendMsg(m)
}

var _RunmMetadata_serviceDesc = grpc.ServiceDesc{
	ServiceName: "runm.RunmMetadata",
	HandlerType: (*RunmMetadataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "bootstrap",
			Handler:    _RunmMetadata_Bootstrap_Handler,
		},
		{
			MethodName: "partition_get",
			Handler:    _RunmMetadata_PartitionGet_Handler,
		},
		{
			MethodName: "object_type_get",
			Handler:    _RunmMetadata_ObjectTypeGet_Handler,
		},
		{
			MethodName: "property_definition_get",
			Handler:    _RunmMetadata_PropertyDefinitionGet_Handler,
		},
		{
			MethodName: "property_definition_delete",
			Handler:    _RunmMetadata_PropertyDefinitionDelete_Handler,
		},
		{
			MethodName: "property_definition_set",
			Handler:    _RunmMetadata_PropertyDefinitionSet_Handler,
		},
		{
			MethodName: "object_get",
			Handler:    _RunmMetadata_ObjectGet_Handler,
		},
		{
			MethodName: "object_delete",
			Handler:    _RunmMetadata_ObjectDelete_Handler,
		},
		{
			MethodName: "object_set",
			Handler:    _RunmMetadata_ObjectSet_Handler,
		},
		{
			MethodName: "object_properties_set",
			Handler:    _RunmMetadata_ObjectPropertiesSet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "partition_list",
			Handler:       _RunmMetadata_PartitionList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "object_type_list",
			Handler:       _RunmMetadata_ObjectTypeList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "property_definition_list",
			Handler:       _RunmMetadata_PropertyDefinitionList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "object_list",
			Handler:       _RunmMetadata_ObjectList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "object_properties_list",
			Handler:       _RunmMetadata_ObjectPropertiesList_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_6147864b9035fd4a) }

var fileDescriptor_service_6147864b9035fd4a = []byte{
	// 1143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0xeb, 0x6e, 0xe3, 0x44,
	0x14, 0x8e, 0x9b, 0x6c, 0xba, 0x39, 0xb9, 0x76, 0xba, 0x6d, 0xbd, 0x2e, 0xb0, 0xa9, 0xf7, 0x56,
	0x15, 0x6d, 0x14, 0x05, 0x84, 0x16, 0x21, 0x40, 0xad, 0xb6, 0x05, 0xa4, 0x2d, 0xa9, 0x66, 0xbb,
	0x48, 0x2b, 0x04, 0x91, 0x5b, 0x4f, 0x8b, 0x77, 0xe3, 0x0b, 0x1e, 0xbb, 0x28, 0x12, 0x12, 0x12,
	0x0f, 0x80, 0xc4, 0x0f, 0x84, 0x90, 0x78, 0x01, 0x1e, 0x85, 0x37, 0xe0, 0x0f, 0xef, 0x82, 0x3c,
	0x33, 0xb6, 0x27, 0x8e, 0x9d, 0x96, 0x20, 0xba, 0xff, 0x3a, 0xe7, 0x7c, 0x73, 0x2e, 0xdf, 0x39,
	0x73, 0x7c, 0x1a, 0x68, 0x52, 0xe2, 0x5f, 0x58, 0xa7, 0xa4, 0xe7, 0xf9, 0x6e, 0xe0, 0xa2, 0x8a,
	0x1f, 0x3a, 0xb6, 0x56, 0x27, 0xbe, 0xef, 0xfa, 0x5c, 0xa4, 0xb5, 0x3c, 0xdf, 0xf5, 0x88, 0x1f,
	0x4c, 0xc4, 0xb9, 0xe1, 0x9e, 0xbc, 0x24, 0xa7, 0x81, 0x38, 0xad, 0xf0, 0xd3, 0x28, 0x98, 0x78,
	0xc2, 0x86, 0xd6, 0xf6, 0x0c, 0x3f, 0xb0, 0x02, 0xcb, 0x75, 0xe2, 0x1b, 0x94, 0x18, 0xfe, 0xe9,
	0x37, 0xe2, 0xd4, 0xa4, 0x84, 0xd2, 0x54, 0xd9, 0xfa, 0xce, 0x37, 0x3c, 0x8f, 0xf8, 0x94, 0x9f,
	0xf5, 0xdf, 0x15, 0xe8, 0xec, 0xb9, 0x6e, 0x40, 0x03, 0xdf, 0xf0, 0x30, 0xf9, 0x36, 0x24, 0x34,
	0x40, 0x0f, 0xa1, 0x7d, 0x12, 0xcb, 0x46, 0x81, 0xfb, 0x8a, 0x38, 0xaa, 0xd2, 0x55, 0xb6, 0x6b,
	0xb8, 0x95, 0x88, 0x8f, 0x23, 0x29, 0xba, 0x0f, 0xad, 0xc4, 0xfb, 0xc8, 0x31, 0x6c, 0xa2, 0x2e,
	0x31, 0x5c, 0x33, 0x91, 0x7e, 0x6e, 0xd8, 0x04, 0x3d, 0x96, 0x61, 0x61, 0x68, 0x99, 0x6a, 0xb9,
	0xab, 0x6c, 0xd7, 0x07, 0x2b, 0xbd, 0x28, 0xff, 0xde, 0xb3, 0xc0, 0xb7, 0x9c, 0xf3, 0x2f, 0x8c,
	0x71, 0x48, 0xa4, 0x9b, 0xcf, 0x43, 0xcb, 0xd4, 0xf7, 0x60, 0x45, 0x8a, 0x8e, 0x7a, 0xae, 0x43,
	0x09, 0x7a, 0x04, 0xb5, 0x04, 0xc5, 0x02, 0xab, 0x0f, 0xda, 0xdc, 0xd2, 0x51, 0x2c, 0xc6, 0x29,
	0x42, 0xb7, 0x61, 0x35, 0x91, 0x7f, 0x42, 0x82, 0x34, 0xc9, 0x65, 0x41, 0x8d, 0xb0, 0xd1, 0x14,
	0xd1, 0x70, 0x21, 0x8e, 0xb5, 0xe8, 0x11, 0x54, 0xcf, 0xac, 0x71, 0x40, 0x7c, 0x96, 0x5c, 0x7d,
	0xb0, 0x96, 0xf1, 0x75, 0xc0, 0x94, 0x58, 0x80, 0xf4, 0x5f, 0x15, 0xb8, 0x95, 0xe8, 0x9e, 0x5a,
	0x74, 0x11, 0x87, 0xcb, 0xae, 0x17, 0xdd, 0xa6, 0xc2, 0xe3, 0x6a, 0x0c, 0x8c, 0xea, 0x3a, 0xe4,
	0x2a, 0x1c, 0x63, 0xd0, 0x43, 0x28, 0x1b, 0xce, 0x44, 0x2d, 0x77, 0xcb, 0xc5, 0xc1, 0x45, 0x08,
	0xdd, 0x85, 0x5b, 0x43, 0xd6, 0x3e, 0xc7, 0x13, 0x8f, 0x2c, 0xc2, 0x44, 0x2f, 0xc3, 0xc4, 0x3a,
	0xc7, 0xa5, 0x46, 0x33, 0x54, 0xfc, 0xa6, 0xc0, 0x5a, 0xaa, 0xbc, 0x0e, 0x2e, 0xb6, 0x65, 0x2e,
	0x8a, 0xc2, 0x63, 0x64, 0x9c, 0x43, 0x87, 0x2b, 0x16, 0x21, 0x62, 0x27, 0x43, 0x04, 0x92, 0x3d,
	0x65, 0x48, 0xf8, 0x51, 0x89, 0x3d, 0x3d, 0x5b, 0xc0, 0xd3, 0xdb, 0x50, 0x3d, 0x73, 0x7d, 0xdb,
	0x08, 0x98, 0xa7, 0x56, 0x9c, 0xfe, 0x91, 0x31, 0x19, 0xbb, 0x86, 0x79, 0xc0, 0x54, 0x58, 0x40,
	0x90, 0x0a, 0xcb, 0x1e, 0x57, 0xb0, 0x07, 0xd6, 0xc0, 0xf1, 0x51, 0x7f, 0x1f, 0x56, 0xa4, 0x18,
	0xc4, 0x3b, 0xba, 0x07, 0x55, 0x3e, 0x4e, 0x44, 0x0c, 0x0d, 0x39, 0x0b, 0x2c, 0x74, 0xfa, 0xcf,
	0x4a, 0x7c, 0xf7, 0x3a, 0x0a, 0x78, 0x4f, 0x2e, 0x60, 0x1e, 0xad, 0xac, 0x78, 0x26, 0xac, 0x72,
	0xe1, 0x13, 0x32, 0x26, 0x01, 0xf9, 0xd7, 0x41, 0x09, 0x2f, 0x4b, 0xf3, 0xbd, 0x0c, 0xe3, 0xf7,
	0x12, 0x7b, 0x11, 0xbc, 0xad, 0x43, 0x95, 0x4d, 0x6c, 0xaa, 0x2a, 0xdd, 0xf2, 0x76, 0x0d, 0x8b,
	0x13, 0xba, 0x03, 0x75, 0x27, 0xb4, 0x47, 0x26, 0x43, 0x9b, 0x2c, 0xdd, 0x0a, 0x06, 0x27, 0xb4,
	0xf9, 0x7d, 0x53, 0xff, 0x01, 0xde, 0x38, 0x12, 0xd3, 0xfd, 0x09, 0x39, 0xb3, 0x9c, 0x85, 0x47,
	0xd2, 0x7b, 0x99, 0xfe, 0x7b, 0x4b, 0x74, 0xc5, 0x8c, 0xf1, 0x4c, 0x2f, 0xfe, 0xa4, 0xe4, 0x45,
	0xf0, 0x1a, 0xfb, 0xf2, 0x25, 0xbc, 0x59, 0x10, 0x8f, 0xe0, 0xfa, 0x33, 0x58, 0x8d, 0x3f, 0x88,
	0x23, 0x33, 0x41, 0x88, 0xb4, 0xd5, 0xa2, 0xb4, 0x31, 0xf2, 0x66, 0x64, 0xfa, 0x1f, 0x4a, 0x9e,
	0xb3, 0xeb, 0x68, 0xea, 0xbe, 0xdc, 0xd4, 0x97, 0xd5, 0x8a, 0xb5, 0xde, 0xf7, 0x70, 0x67, 0x16,
	0xb0, 0x60, 0xb3, 0xf7, 0xe5, 0x66, 0xbf, 0x92, 0xf7, 0x2f, 0xa1, 0x5b, 0xec, 0xfd, 0xbf, 0x3e,
	0x82, 0xbf, 0x15, 0xd0, 0xf8, 0xb3, 0x12, 0x3e, 0x2c, 0x42, 0x17, 0xe9, 0xc0, 0x74, 0x7a, 0x2d,
	0x15, 0x4f, 0x2f, 0xd4, 0x85, 0xb2, 0x61, 0x9a, 0x82, 0xfa, 0xd6, 0x74, 0xf2, 0x38, 0x52, 0xa1,
	0x07, 0x50, 0xf5, 0x89, 0xed, 0x5e, 0x10, 0xb5, 0x92, 0x0b, 0x12, 0xda, 0x08, 0x67, 0xbb, 0xa6,
	0x75, 0x36, 0x51, 0x6f, 0xe4, 0xe3, 0xb8, 0x56, 0xff, 0x53, 0x81, 0xcd, 0xdc, 0xfc, 0x04, 0x71,
	0x77, 0xa7, 0x88, 0xab, 0x0f, 0xea, 0xdc, 0xce, 0x7e, 0x24, 0x4b, 0x58, 0xbc, 0x5a, 0x72, 0x9b,
	0x50, 0x8b, 0xb8, 0x36, 0x4c, 0x93, 0xf0, 0x97, 0x55, 0xc1, 0x37, 0x9d, 0xd0, 0xde, 0x8d, 0xce,
	0x71, 0x21, 0x78, 0xf4, 0xa6, 0x5a, 0x49, 0x0a, 0x81, 0xb9, 0x04, 0x6d, 0x41, 0x23, 0x02, 0xb0,
	0xb0, 0x2d, 0x62, 0xaa, 0x37, 0x18, 0x22, 0xba, 0x74, 0x28, 0x44, 0xfa, 0x64, 0x36, 0x95, 0xe8,
	0xbd, 0xf0, 0x5e, 0xa1, 0x08, 0x41, 0xe5, 0x15, 0x99, 0xc4, 0x1d, 0xc0, 0xfe, 0x8e, 0xfa, 0xe2,
	0x22, 0xda, 0xe4, 0x28, 0x6b, 0xb8, 0x1a, 0x16, 0x27, 0xd4, 0x03, 0xf0, 0x12, 0x23, 0x05, 0xf5,
	0x90, 0x10, 0xfa, 0x5f, 0x4a, 0xbe, 0xef, 0xff, 0xa9, 0x4f, 0x3e, 0x80, 0x65, 0x3e, 0x23, 0xa9,
	0xd8, 0x4d, 0xb7, 0x64, 0x58, 0x6e, 0xfa, 0x38, 0xbe, 0x21, 0x8f, 0x83, 0xca, 0xe5, 0xe3, 0x60,
	0x67, 0x07, 0x9a, 0x53, 0x73, 0x12, 0xdd, 0x84, 0xca, 0x8b, 0xdd, 0xc3, 0xa7, 0x9d, 0x12, 0x6a,
	0x43, 0xfd, 0x08, 0x0f, 0x8f, 0x87, 0x7b, 0xcf, 0x0f, 0x0e, 0xf6, 0x71, 0x47, 0x19, 0xfc, 0x52,
	0x83, 0x06, 0x0e, 0x1d, 0xfb, 0x90, 0x04, 0x86, 0x69, 0x04, 0x06, 0xfa, 0x08, 0x6a, 0xc9, 0x12,
	0x8e, 0xc4, 0x86, 0x93, 0x5d, 0xe0, 0xb5, 0x8d, 0x19, 0x39, 0x6f, 0x3e, 0xbd, 0x84, 0x3e, 0x84,
	0x74, 0xc5, 0x1e, 0x9d, 0x93, 0x00, 0xdd, 0xce, 0x6c, 0x8c, 0xe9, 0xf7, 0x48, 0xcb, 0x6e, 0xd5,
	0x7a, 0x09, 0xed, 0xca, 0xab, 0xfc, 0xd8, 0xa2, 0x01, 0xd2, 0x32, 0x20, 0xa9, 0x48, 0x39, 0x06,
	0xfa, 0x0a, 0xda, 0x85, 0xb6, 0xf4, 0x5f, 0x0c, 0x8b, 0x41, 0xcb, 0x6e, 0x6a, 0x52, 0x10, 0x9d,
	0xac, 0x4e, 0x2f, 0xa1, 0x7d, 0xe8, 0xc8, 0x26, 0x58, 0x1c, 0x9b, 0x59, 0x9c, 0x1c, 0x48, 0x8e,
	0x91, 0xbe, 0x82, 0x5e, 0xc0, 0x46, 0xce, 0xc7, 0x85, 0x45, 0xa4, 0x17, 0xcd, 0x49, 0x29, 0xb2,
	0xc2, 0xcf, 0x8f, 0x5e, 0x42, 0x36, 0x68, 0x79, 0xa6, 0xf9, 0x58, 0x44, 0xf7, 0x8b, 0x6e, 0x4e,
	0x8d, 0x78, 0xed, 0xc1, 0x65, 0xb0, 0xa4, 0xaa, 0x66, 0x7e, 0x26, 0x74, 0x5e, 0x26, 0xe9, 0xd0,
	0xd5, 0xee, 0xce, 0xc5, 0x24, 0x5e, 0xbe, 0x02, 0x35, 0xcf, 0x0b, 0xa3, 0xbf, 0xd0, 0x84, 0x5c,
	0x86, 0x39, 0x8c, 0xf5, 0x15, 0xf4, 0x2e, 0x80, 0xa8, 0x6a, 0x54, 0x81, 0xa9, 0xed, 0x5d, 0x62,
	0x7d, 0xea, 0xfd, 0xea, 0x25, 0xf4, 0x29, 0x34, 0xc5, 0x2d, 0x41, 0xee, 0x6d, 0x19, 0x30, 0x4d,
	0xa8, 0x96, 0xa7, 0x4a, 0xd2, 0xfb, 0x38, 0xf1, 0x4f, 0xb3, 0xfe, 0x25, 0xae, 0x36, 0x66, 0xe4,
	0x89, 0x81, 0xc7, 0x50, 0x17, 0x06, 0x18, 0x25, 0x53, 0x48, 0x99, 0x86, 0x4c, 0x0a, 0x7d, 0x05,
	0x7d, 0x0d, 0x6b, 0xe2, 0x66, 0x3a, 0x02, 0x59, 0x14, 0xdd, 0xfc, 0x31, 0x24, 0xc5, 0xb3, 0x35,
	0x07, 0x91, 0x44, 0x36, 0x84, 0xf5, 0x59, 0xfb, 0x2c, 0xc8, 0x39, 0x73, 0x2e, 0xf6, 0x90, 0x19,
	0xd3, 0x51, 0xc0, 0x27, 0x55, 0xf6, 0xf3, 0xc1, 0x3b, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x8e,
	0x07, 0xdb, 0xe9, 0xd1, 0x10, 0x00, 0x00,
}
